title: "Jongeun Baek"
description: "AI Researcher — Reliable NLP/LLMs, Hallucination, Mechanistic Interpretability"
# 본인 이름(퍼블리케이션에서 bold 처리 기준)
owner_name: "Jong-eun Baek"

# GitHub Pages 루트 저장소면 baseurl은 비워둡니다.
url: "https://baek26.github.io"
baseurl: ""

# (테마 플러그인 없이) 커스텀 레이아웃 사용
markdown: kramdown
kramdown:
  input: GFM

# 사이트 네비게이션 메뉴 (사이드바에서 사용)
nav:
  - title: "About"
    url: "/#about"
  - title: "News"
    url: "/#news"
  - title: "Publications"
    url: "/#publications"
  - title: "CV"
    url: "/cv/"

# 소셜/링크
profile:
  role: "M.S. Student @ KAIST SAIL"
  affiliation: "Advisor: Prof. Jaesik Choi"
  location: "Seoul, South Korea"
  email: "jongeun.baek@kaist.ac.kr"
  github: "https://github.com/BAEK26"
  scholar: "https://scholar.google.com/citations?user=SaSaOY4AAAAJ"
  linkedin: "https://www.linkedin.com/in/baek26/"

# 빌드에서 제외할 파일/폴더
exclude:
  - README.md
  - node_modules
  - package.json

# Google Analytics (GA4 measurement ID)
google_analytics: "G-049768N7XH"
